version: "3.6"

services:    
  python:
    depends_on:
      - db
    network_mode: "service:db"
    image: python:3.11
    container_name: python
    restart: unless-stopped
    stdin_open: true
    volumes:
      - .:/app:z
    build:
      context: .
      dockerfile: python.Dockerfile
    working_dir: /app
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=server.py
      - DEV_DATABASE_URL=mysql+pymysql://user:secret@localhost:3306/prices
  db:
    container_name: db
    image: mysql:5.7
    restart: unless-stopped
    command: --init-file /app/database/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: prices
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
      - 5000:5000
    volumes:
      - my-db:/var/lib/mysql:rw
      - ./app/database/init.sql:/app/database/init.sql
volumes:
  my-db:
    driver: local